# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-spaceship

# 3. Gem settings
paginate: 4 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: DavidDarnes # jekyll-seo-tag > Owners twitter username
# author: DavidDarnes # jekyll-seo-tag > default author
# social: # jekyll-seo-tag > social overrides
#   name: David Darnes # jekyll-seo-tag > real name
#   links:  # jekyll-seo-tag > social aliases (sameAs)
#     - https://twitter.com/DavidDarnes
#     - https://www.facebook.com/daviddarnes
#     - https://www.linkedin.com/in/daviddarnes
#     - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
# markdown: kramdown
# highlighter: rouge
# input: GFM

  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    # description: "Posts" # The post list page content
    # feature_image: "medieval_guild.jpg"
    #
    # feature_text: |
    #    credits: https://genealogybeyondthebmd.blogspot.com/2014/05/guilds-and-apprenticeships.html

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "The Machinery" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/book-icon-transparent.png" # Site logo, also used in jekyll-seo-tag
description: "Personal blog about systems engineering and research" # Site description and default description, also used in jekyll-seo-tag
# url: "https://alembic.darn.es" # Site url, also used in jekyll-seo-tag
baseurl: ""
# repo: "https://github.com/daviddarnes/alembic"
# email: "me@daviddarnes.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: "/assets/logos/book-icon-transparent.png" 
  32: "/assets/logos/book-icon-transparent.png"
  96: "/assets/logos/book-icon-transparent.png" 
  120: "/assets/logos/book-icon-transparent.png"
  144: "/assets/logos/book-icon-transparent.png"
  180: "/assets/logos/book-icon-transparent.png"
  512: "/assets/logos/book-icon-transparent.png"
  1024: "/assets/logos/book-icon-transparent.png"

# 9. Site navigation
navigation_header:
# - title: Elements
#   url: /elements/
- title: Blog
  url: /
- title: About
  url: /about/
# - title: Categories
#   url: /categories/
# - title: Search
#   url: /search/

navigation_footer:
- title: Home
  url: /
#   url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://linkedin.com/in/michał-podleś-3b4864186
  GitHub: https://github.com/mpodles
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: 'https://mermaid.ink/img/'
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
